"""migrate3

Revision ID: 3f89bbacebfa
Revises: 49bdac9a3748
Create Date: 2024-09-27 01:36:15.281262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f89bbacebfa'
down_revision: Union[str, None] = '49bdac9a3748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'worm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('worm', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
