"""create databases

Revision ID: 6a7c5a16347e
Revises: 
Create Date: 2024-11-09 21:04:33.339348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a7c5a16347e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NAME', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_players_NAME'), 'players', ['NAME'], unique=True)
    op.create_table('matches',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UUID', mysql.CHAR(length=36), nullable=False),
    sa.Column('player1', sa.Integer(), nullable=False),
    sa.Column('player2', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('score', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['player1'], ['players.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player2'], ['players.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner'], ['players.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('UUID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_index(op.f('ix_players_NAME'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
