"""score nullable=True

Revision ID: 72e7d6928418
Revises: 3f89bbacebfa
Create Date: 2024-10-10 23:43:46.866009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '72e7d6928418'
down_revision: Union[str, None] = '3f89bbacebfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'winner',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('matches', 'score',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'score',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('matches', 'winner',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
